lab_1/urls.py
from django.conf.urls import url
from .views import index
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
]

lab_7/urls.py
from django.conf.urls import url
from .views import index, add_friend, validate_npm, delete_friend, friend_list_json, friend_list

urlpatterns = [
     url(r'^$', index, name='index'),
     url(r'^add-friend/$', add_friend, name='add-friend'),
     url(r'^validate-npm/$', validate_npm, name='validate-npm'),
     url(r'^delete-friend/$', delete_friend, name='delete-friend'),
     url(r'^get-friend-list/$', friend_list_json, name='get-friend-list'),
     url(r'^friend-list/$', friend_list, name='friend_list'),
]

praktikum/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
import lab_1.urls as lab_1
import lab_2.urls as lab_2
import lab_2_addon.urls as lab_2_addon
import lab_3.urls as lab_3
import lab_4.urls as lab_4
import lab_5.urls as lab_5
import lab_6.urls as lab_6
import lab_7.urls as lab_7
import lab_8.urls as lab_8
import lab_9.urls as lab_9
from lab_1.views import index as index_lab1
from lab_2.views import index as landing_page


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^lab-1/', include(lab_1, namespace='lab-1')),
    url(r'^lab-2/', include(lab_2, namespace='lab-2')),
    url(r'^lab-2-addon/', include(lab_2_addon, namespace='lab-2-addon')),
    url(r'^lab-3/', include(lab_3, namespace='lab-3')),
    url(r'^lab-4/', include(lab_4, namespace='lab-4')),
    url(r'^lab-5/', include(lab_5, namespace='lab-5')),
    url(r'^lab-6/', include(lab_6, namespace='lab-6')),
    url(r'^lab-7/', include(lab_7, namespace='lab-7')),
    url(r'^lab-8/', include(lab_8, namespace='lab-8')),
    url(r'^lab-9/', include(lab_9, namespace='lab-9')),
    url(r'^$', RedirectView.as_view(url='lab-4/', permanent=True), name='index')
]

lab_7/models.py
from django.db import models

class Friend(models.Model):
    friend_name = models.CharField(max_length=400)
    npm = models.CharField(max_length=250)
    added_at = models.DateField(auto_now_add=True)

lab_7/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.core import serializers

from .models import Friend
from .api_csui_helper.csui_helper import CSUIhelper
import os
import json

response = {}
csui_helper = CSUIhelper()

def index(request):
    page_number = request.GET.get("page", 1)
    mahasiswa_list = csui_helper.instance.get_mahasiswa_list(page_number)

    friend_list = Friend.objects.all()
    response = {"mahasiswa_list": mahasiswa_list, "friend_list": friend_list, "page": page_number}
    html = 'lab_7/lab_7.html'
    return render(request, html, response)

def friend_list(request):
    friend_list = Friend.objects.all()
    response['friend_list'] = friend_list
    html = 'lab_7/daftar_teman.html'
    return render(request, html, response)

@csrf_exempt
def add_friend(request):
    if request.method == 'POST':
        name = request.POST['name']
        npm = request.POST['npm']
        is_taken = False
        friend_list = Friend.objects.all()
        for friend in friend_list:
            if npm == friend.npm:
                is_taken = True
        if is_taken:
            return HttpResponse(None)
        friend = Friend(friend_name=name, npm=npm)
        friend.save()
        data = model_to_dict(friend)
        return HttpResponse(data)

@csrf_exempt
def delete_friend(request):
    friend_id = request.POST.get('id', None)
    Friend.objects.filter(id=friend_id).delete()
    return HttpResponse()

@csrf_exempt
def validate_npm(request):
    npm = request.POST.get('npm', None)
    is_taken = False
    friend_list = Friend.objects.all()
    for friend in friend_list:
        if npm == friend.npm:
            is_taken = True

    data = {
        'is_taken': is_taken
    }
    return JsonResponse(data)

def model_to_dict(obj):
    data = serializers.serialize('json', [obj,])
    struct = json.loads(data)
    data = json.dumps(struct[0]["fields"])
    return data

def friend_list_json(request):
    if request.method == 'GET':
        friend_list = Friend.objects.all()
        data = serializers.serialize('json', friend_list)
        return HttpResponse(data)

lab_7/templates/lab_7/daftar_teman.html
{% extends "lab_7/layout/base.html" %}

{% block content %}
    <section name="friend-list">
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-lg-8">
                    <h2> friend Fasilkom</h2>
                    <div id="friend-list" class="list-group">

                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}
{% block javascript %}
    <script>
        $(document).ready(function() {
            $.ajax({
                method: "GET",
                url: "{% url 'lab-7:get-friend-list' %}",
                success: function(response) {
                    var friend_list = JSON.parse(response);
                    if (friend_list.length === 0)
                        $('#friend-list').append('<span class="list-group-item alert-danger text-center">Tidak ada teman</span>')
                    $.each(friend_list, function(index, friend) {
                        var button = '<button type="button" class="pull-right btn btn-xs btn-danger"' +
                            'onClick="deleteFriend(' + friend.pk + ')">' +
                            '&times; Remove Friend' +
                            '</button>' +
                            '</div>';
                        var html = '<div class="list-group-item clearfix">' + friend.fields.friend_name + '</a>' + button;

                        $("#friend-list").append(html)
                    })

                },
                error: function(error) {
                    $('#friend-list').append("Tidak ada teman")
                }
            });
        });

        function deleteFriend(id) {
            /*alert("Apakah Anda akan menghapus " + friend.friend_name + " dari daftar teman?");*/
            $.ajax({
                method: "POST",
                url: '{% url "lab-7:delete-friend" %}',
                data: {
                    'id': id
                },
                dataType: 'json',
            });
            window.open('../friend-list/', '_self')
        }
    </script>
{% endblock %}

lab_7/templates/lab_7/lab_7.html
{% extends "lab_7/layout/base.html" %}
{% block content %}
<section name="mahasiswa-list" id="mahasiswa-list">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-lg-8">
                <h2> Mahasiswa Fasilkom</h2>
                <div class="list-group">
                    {% if mahasiswa_list %}
                        {% for mahasiswa in mahasiswa_list %}
                            <a class="list-group-item clearfix">
                                {{ mahasiswa.nama }} ({{ mahasiswa.npm }})
                                <span class="pull-right">
                        <span class="btn btn-xs btn-default" onClick="addFriend('{{ mahasiswa.nama }}', '{{ mahasiswa.npm }}')">
                            Tambah sebagai teman
                        </span>
                    </span>
                            </a>
                        {% endfor %}
                    {% else %}
                        <div class="alert alert-danger text-center">
                            <strong>Opps!</strong> Tidak ada mahasiswa
                        </div>
                    {% endif %}
                </div>
                <div>
                    <a class="btn btn-default" href="/lab-7/?page={{ page|add:-1 }}">
                        <span class="glyphicon glyphicon-arrow-left"></span>
                    </a>
                    <a class="btn btn-default" href="/lab-7/?page={{ page|add:1 }}">
                        <span class="glyphicon glyphicon-arrow-right"></span>
                    </a>
                </div>
            </div>
            <div class="col-lg-4">
                <h2> Teman Saya </h2>
                <div class="list-group" id="friend-list">
                    {% if friend_list %}
                        {% for friend in friend_list %}
                            <a class="list-group-item clearfix">
                                {{ friend.friend_name }} ({{ friend.npm }})
                            </a>
                        {% endfor %}
                    {% else %}
                        <div class="alert alert-danger text-center">
                            <strong>Opps!</strong> Tidak ada teman
                        </div>
                    {% endif %}
                </div>
                <form id="add-friend" action="#">
                    {% csrf_token %}
                    <label for="field_npm">npm</label>
                    <input id="field_npm" type="text" name="npm" class="form-control"/>
                    <label for="field_name">name</label>
                    <input id="field_name" type="text" name="name" class="form-control"/>
                    <button type="submit">Tambah</button>
                </form>
            </div>
        </div>
    </div>
</section>
{% block javascript %}
<script>
    var addFriend = function(nama, npm) {
        $.ajax({
            method: "POST",
            url: "{% url "lab-7:add-friend" %}",
            data: { name: nama, npm: npm},
            dataType: 'json',
            success : function (friend) {
                if (friend === null){
                    alert("Mahasiswa tersebut sudah ditambahkan sebagai teman")
                }else{
                    html = '<a class="list-group-item clearfix">' +
                        friend.friend_name + ' (' + friend.npm + ')'
                        '</a>';
                    $("#friend-list").append(html)
                }
            },
            error : function (error) {
                alert("Mahasiswa tersebut sudah ditambahkan sebagai teman")
            }
        });
    };

    $("#add-friend").on("submit", function () {
       name = $("#field_name").val()
       npm = $("#field_npm").val()
        addFriend(name, npm)
        event.preventDefault();
    });

    $("#field_npm").change(function () {
        console.log($(this).val() );
        npm = $(this).val();
        $.ajax({
            method: "POST",
            url: '{% url "lab-7:validate-npm" %}',
            data: {
                'npm': npm
            },
            dataType: 'json',
            success: function (data) {
                if (data.is_taken) {
                    alert("Mahasiswa dengan npm seperti ini sudah ada");
                }
            },
            error: function (error) {
                alert("Mahasiswa dengan npm seperti ini sudah ada");
            }
        });
    });
</script>
{% endblock %}

{% endblock %}